// <auto-generated />
namespace Language_Swopper_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TableEditAll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableEditAll));
        
        string IMigrationMetadata.Id
        {
            get { return "201808200315254_Table-Edit All"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
